#FROM node:14.17.0-alpine as build-step
#EXPOSE 80
#RUN mkdir -p /app
#WORKDIR /app
##COPY package.json /app
#RUN npm install
#COPY . /app
#RUN npm run build --prod
#FROM node:latest as build
#EXPOSE 80
#WORKDIR /app
#COPY . .
#RUN npm install
#RUN npm run build
#CMD ["node", "src/index.js"]

FROM node:alpine AS my-app-build
WORKDIR /app
COPY . .
RUN npm ci && npm run build

FROM nginx:alpine
COPY --from=my-app-build /app/dist/front /usr/share/nginx/html
EXPOSE 80
